controller updated to return negative amount if id is from account
FinnieRyan/IP3-Banking-App-project pull request #32
Opened 2024-06-10 13:40 UTC by Dudge1991

2024-06-10 13:58 UTC, DarylGrant approved these changes, later dismissed

2024-06-10 14:22 UTC, alexkinsey requested changes

2024-06-10 14:22 UTC, alexkinsey commented on server/controllers/transactionController.js
> +        amount = -amount; // Convert balance to negative if transaction is from the specified account
I'm still unsure if this will do everything we need. So we know if transfers between accounts are negative or positive based on the id, but what about transactions external to an account, am I paying or being paid by Netflix etc. How does the database represent refunds from vendors? I was expecting almost all the amounts to be negative as they are all payments to a vendor

2024-06-10 17:48 UTC, Dudge1991 commented on server/controllers/transactionController.js
> +        amount = -amount; // Convert balance to negative if transaction is from the specified account
I've updated this PR to remove the controller changes.

The seed data now provides an negative amount for all transactions. The only positive transaction is a Salary on the 1st of each month for the last 2 years.

2024-06-11 20:28 UTC, alexkinsey approved these changes

2024-06-11 20:33 UTC, DarylGrant approved these changes

2024-06-11 20:33 UTC, merged