More tests added for database and server
FinnieRyan/IP3-Banking-App-project pull request #43
Opened 2024-06-14 09:18 UTC by DarylGrant

2024-06-14 09:45 UTC, Dudge1991 requested changes

2024-06-14 09:45 UTC, Dudge1991 commented on server/controllers/accountController.test.js
> +    await mongoose.connect(process.env.DB_URI);
The controller tests are connecting to the live DB. I think you need to youse MongoMemoryServer in these files similar to what you have done in the models tests.

2024-06-14 10:30 UTC, Dudge1991 commented on server/controllers/accountController.test.js
> +    await mongoose.connect(process.env.DB_URI);
Can you also update the database/config/helpers.test.js to include the below as it's causing an error with not being able to find the DB_URI string.

`import dotenv from 'dotenv';

dotenv.config();`

2024-06-14 15:21 UTC, Dudge1991 approved these changes

2024-06-24 09:30 UTC, alexkinsey approved these changes

2024-06-24 09:32 UTC, merged