Feat: configuring backend with database
FinnieRyan/IP3-Banking-App-project pull request #7
Opened 2024-05-24 13:13 UTC by FinnieRyan

### Summary of the PR:

- Restructured the file hierarchy to incorporate environment variables for database connectivity.
- Authentication server capabilities now include user registration, login, and access token generation.
- The server can utilize the access token to reach a bare protected endpoint.
- Added a basic Postman collection to demonstrate this flow.
- Implemented a pre-commit Git hook with the Prettier extension for consistent code formatting.

2024-05-24 13:18 UTC, DarylGrant approved these changes, later dismissed

2024-05-24 14:17 UTC, DarylGrant approved these changes, later dismissed

2024-05-27 09:36 UTC, alexkinsey requested changes

2024-05-27 09:36 UTC, alexkinsey commented on .prettierrc
> +  "semi": false,
I think this semi colon attribute should be set to true. It looks like it's causing edits in every file due to it removing semi colons

2024-05-27 09:49 UTC, DarylGrant submitted a review, later dismissed

2024-05-29 13:07 UTC, alexkinsey approved these changes

2024-05-29 14:27 UTC, Dudge1991 approved these changes

2024-05-29 14:33 UTC, merged